import "../public/styles/index.scss";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import PageTransition from "./components/commons/wrapper/page-transition";
import ReactLenis from "lenis/react";
import SWRConfigWrapper from "./components/commons/wrapper/swr-config";

const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PV Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <PageTransition>
          <SWRConfigWrapper>
            <ReactLenis root>{children}</ReactLenis>
          </SWRConfigWrapper>
        </PageTransition>
      </body>
    </html>
  );
}
